// automatically generated by the FlatBuffers compiler, do not modify

package overlay_protocol;

@SuppressWarnings("unused")
public final class BoneType {
  private BoneType() { }
  public static final int Head = 0;
  public static final int Neck = 1;
  public static final int Chest = 2;
  public static final int Waist = 3;
  public static final int Hip = 4;
  public static final int ThighL = 5;
  public static final int ThighR = 6;
  public static final int AnkleL = 7;
  public static final int AnkleR = 8;
  public static final int FootL = 9;
  public static final int FootR = 10;
  public static final int WristL = 11;
  public static final int WristR = 12;
  public static final int ForeArmL = 13;
  public static final int ForeArmR = 14;
  public static final int UpperArmL = 15;
  public static final int UpperArmR = 16;

  public static final String[] names = { "Head", "Neck", "Chest", "Waist", "Hip", "ThighL", "ThighR", "AnkleL", "AnkleR", "FootL", "FootR", "WristL", "WristR", "ForeArmL", "ForeArmR", "UpperArmL", "UpperArmR", };

  public static String name(int e) { return names[e]; }
}

