// automatically generated by the FlatBuffers compiler, do not modify

package overlay_protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class OutboundPacketT {
  private overlay_protocol.BonePoseT[] bones;

  public overlay_protocol.BonePoseT[] getBones() { return bones; }

  public void setBones(overlay_protocol.BonePoseT[] bones) { this.bones = bones; }


  public OutboundPacketT() {
    this.bones = null;
  }
}

