// automatically generated by the FlatBuffers compiler, do not modify

package overlay_protocol;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class Vec3fT {
  private float x;
  private float y;
  private float z;

  public float getX() { return x; }

  public void setX(float x) { this.x = x; }

  public float getY() { return y; }

  public void setY(float y) { this.y = y; }

  public float getZ() { return z; }

  public void setZ(float z) { this.z = z; }


  public Vec3fT() {
    this.x = 0.0f;
    this.y = 0.0f;
    this.z = 0.0f;
  }
}

