packages:
  - "solarxr-protocol"
  - "gui/app"
  - "gui/electron"
  - "gui/shared"
  - "!solarxr-protocol/lib/flatbuffers/**"

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - 'electron'
  - 'electron-winstaller'
  - 'esbuild'
  - 'register-scheme'
  - 'unrs-resolver'
