packages:
  - "solarxr-protocol"
  - "gui"
  - "!solarxr-protocol/lib/flatbuffers/**"

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - electron
  - electron-winstaller
  - esbuild
  - register-scheme
  - unrs-resolver
