/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.3/userguide/multi_project_builds.html
 */

rootProject.name = "SlimeVR Server"

pluginManagement {
	repositories {
		gradlePluginPortal()
		google()
		mavenCentral()
//		mavenLocal()
		maven {
			url = uri("https://oss.sonatype.org/content/repositories/snapshots")
		}
	}

	val robovmVersion: String by settings
	resolutionStrategy {
		eachPlugin {
			if (requested.id.name == "robovm") {
				useModule("com.robovmx:robovm-gradle-plugin:${requested.version ?: robovmVersion}")
			}
		}
	}

	val kotlinVersion: String by settings
	val spotlessVersion: String by settings
	val shadowJarVersion: String by settings
	val buildconfigVersion: String by settings
	val grgitVersion: String by settings
	plugins {
		kotlin("plugin.serialization") version kotlinVersion
		kotlin("jvm") version kotlinVersion
		kotlin("android") version kotlinVersion
		id("com.diffplug.spotless") version spotlessVersion
		id("com.gradleup.shadow") version shadowJarVersion
		id("com.github.gmazzo.buildconfig") version buildconfigVersion
		id("org.ajoberstar.grgit") version grgitVersion
		id("robovm") version robovmVersion apply false
	}
}

include(":solarxr-protocol")
project(":solarxr-protocol").projectDir = File("solarxr-protocol/protocol/java")

include(":server")
project(":server").projectDir = File("server")
include(":server:core")
include(":server:desktop")
include(":server:android")
include(":server:ios")
