package dev.slimevr.vmc

import solarxr_protocol.datatypes.BodyPart

enum class UnityBone(
	val serial: String,
	val bodyParts: Array<BodyPart>,
) {
	// Spine
	HEAD("Head", arrayOf(BodyPart.HEAD)),
	NECK("Neck", arrayOf(BodyPart.NECK)),
	UPPER_CHEST("UpperChest", arrayOf(BodyPart.UPPER_CHEST)),
	CHEST("Chest", arrayOf(BodyPart.LOWER_CHEST)),
	SPINE(
		"Spine",
		arrayOf(
			BodyPart.UPPER_WAIST,
			BodyPart.LOWER_WAIST,
		),
	),
	HIPS("Hips", arrayOf(BodyPart.HIP)),

	// Arms
	LEFT_SHOULDER("LeftShoulder", arrayOf(BodyPart.LEFT_SHOULDER)),
	RIGHT_SHOULDER("RightShoulder", arrayOf(BodyPart.RIGHT_SHOULDER)),
	LEFT_UPPER_ARM("LeftUpperArm", arrayOf(BodyPart.LEFT_UPPER_ARM)),
	RIGHT_UPPER_ARM("RightUpperArm", arrayOf(BodyPart.RIGHT_UPPER_ARM)),
	LEFT_LOWER_ARM("LeftLowerArm", arrayOf(BodyPart.LEFT_LOWER_ARM)),
	RIGHT_LOWER_ARM("RightLowerArm", arrayOf(BodyPart.RIGHT_LOWER_ARM)),
	LEFT_HAND("LeftHand", arrayOf(BodyPart.LEFT_HAND)),
	RIGHT_HAND("RightHand", arrayOf(BodyPart.RIGHT_HAND)),

	// Legs
	LEFT_UPPER_LEG("LeftUpperLeg", arrayOf(BodyPart.LEFT_UPPER_LEG)),
	RIGHT_UPPER_LEG("RightUpperLeg", arrayOf(BodyPart.RIGHT_UPPER_LEG)),
	LEFT_LOWER_LEG("LeftLowerLeg", arrayOf(BodyPart.LEFT_LOWER_LEG)),
	RIGHT_LOWER_LEG("RightLowerLeg", arrayOf(BodyPart.RIGHT_LOWER_LEG)),
	LEFT_FOOT("LeftFoot", arrayOf(BodyPart.LEFT_FOOT)),
	RIGHT_FOOT("RightFoot", arrayOf(BodyPart.RIGHT_FOOT)),

	// Fingers
	LEFT_THUMB_PROXIMAL("LeftThumbProximal", arrayOf(BodyPart.LEFT_THUMB_METACARPAL)),
	LEFT_THUMB_INTERMEDIATE("LeftThumbIntermediate", arrayOf(BodyPart.LEFT_THUMB_PROXIMAL)),
	LEFT_THUMB_DISTAL("LeftThumbDistal", arrayOf(BodyPart.LEFT_THUMB_DISTAL)),
	LEFT_INDEX_PROXIMAL("LeftIndexProximal", arrayOf(BodyPart.LEFT_INDEX_PROXIMAL)),
	LEFT_INDEX_INTERMEDIATE("LeftIndexIntermediate", arrayOf(BodyPart.LEFT_INDEX_INTERMEDIATE)),
	LEFT_INDEX_DISTAL("LeftIndexDistal", arrayOf(BodyPart.LEFT_INDEX_DISTAL)),
	LEFT_MIDDLE_PROXIMAL("LeftMiddleProximal", arrayOf(BodyPart.LEFT_MIDDLE_PROXIMAL)),
	LEFT_MIDDLE_INTERMEDIATE("LeftMiddleIntermediate", arrayOf(BodyPart.LEFT_MIDDLE_INTERMEDIATE)),
	LEFT_MIDDLE_DISTAL("LeftMiddleDistal", arrayOf(BodyPart.LEFT_MIDDLE_DISTAL)),
	LEFT_RING_PROXIMAL("LeftRingProximal", arrayOf(BodyPart.LEFT_RING_PROXIMAL)),
	LEFT_RING_INTERMEDIATE("LeftRingIntermediate", arrayOf(BodyPart.LEFT_RING_INTERMEDIATE)),
	LEFT_RING_DISTAL("LeftRingDistal", arrayOf(BodyPart.LEFT_RING_DISTAL)),
	LEFT_LITTLE_PROXIMAL("LeftLittleProximal", arrayOf(BodyPart.LEFT_LITTLE_PROXIMAL)),
	LEFT_LITTLE_INTERMEDIATE("LeftLittleIntermediate", arrayOf(BodyPart.LEFT_LITTLE_INTERMEDIATE)),
	LEFT_LITTLE_DISTAL("LeftLittleDistal", arrayOf(BodyPart.LEFT_LITTLE_DISTAL)),

	RIGHT_THUMB_PROXIMAL("RightThumbProximal", arrayOf(BodyPart.RIGHT_THUMB_METACARPAL)),
	RIGHT_THUMB_INTERMEDIATE("RightThumbIntermediate", arrayOf(BodyPart.RIGHT_THUMB_PROXIMAL)),
	RIGHT_THUMB_DISTAL("RightThumbDistal", arrayOf(BodyPart.RIGHT_THUMB_DISTAL)),
	RIGHT_INDEX_PROXIMAL("RightIndexProximal", arrayOf(BodyPart.RIGHT_INDEX_PROXIMAL)),
	RIGHT_INDEX_INTERMEDIATE("RightIndexIntermediate", arrayOf(BodyPart.RIGHT_INDEX_INTERMEDIATE)),
	RIGHT_INDEX_DISTAL("RightIndexDistal", arrayOf(BodyPart.RIGHT_INDEX_DISTAL)),
	RIGHT_MIDDLE_PROXIMAL("RightMiddleProximal", arrayOf(BodyPart.RIGHT_MIDDLE_PROXIMAL)),
	RIGHT_MIDDLE_INTERMEDIATE("RightMiddleIntermediate", arrayOf(BodyPart.RIGHT_MIDDLE_INTERMEDIATE)),
	RIGHT_MIDDLE_DISTAL("RightMiddleDistal", arrayOf(BodyPart.RIGHT_MIDDLE_DISTAL)),
	RIGHT_RING_PROXIMAL("RightRingProximal", arrayOf(BodyPart.RIGHT_RING_PROXIMAL)),
	RIGHT_RING_INTERMEDIATE("RightRingIntermediate", arrayOf(BodyPart.RIGHT_RING_INTERMEDIATE)),
	RIGHT_RING_DISTAL("RightRingDistal", arrayOf(BodyPart.RIGHT_RING_DISTAL)),
	RIGHT_LITTLE_PROXIMAL("RightLittleProximal", arrayOf(BodyPart.RIGHT_LITTLE_PROXIMAL)),
	RIGHT_LITTLE_INTERMEDIATE("RightLittleIntermediate", arrayOf(BodyPart.RIGHT_LITTLE_INTERMEDIATE)),
	RIGHT_LITTLE_DISTAL("RightLittleDistal", arrayOf(BodyPart.RIGHT_LITTLE_DISTAL)),

	// Toes
	LEFT_TOES(
		"LeftToes",
		arrayOf(
			BodyPart.LEFT_BIG_TOE,
			BodyPart.LEFT_INDEX_TOE,
			BodyPart.LEFT_MIDDLE_TOE,
			BodyPart.LEFT_RING_TOE,
			BodyPart.LEFT_LITTLE_TOE,
		),
	),
	RIGHT_TOES(
		"RightToes",
		arrayOf(
			BodyPart.RIGHT_BIG_TOE,
			BodyPart.RIGHT_INDEX_TOE,
			BodyPart.RIGHT_MIDDLE_TOE,
			BodyPart.RIGHT_RING_TOE,
			BodyPart.RIGHT_LITTLE_TOE,
		),
	),

	// Custom toes
	LEFT_BIG_TOE("LeftBigToe", arrayOf(BodyPart.LEFT_BIG_TOE)),
	LEFT_INDEX_TOE("LeftIndexToe", arrayOf(BodyPart.LEFT_INDEX_TOE)),
	LEFT_MIDDLE_TOE("LeftMiddleToe", arrayOf(BodyPart.LEFT_MIDDLE_TOE)),
	LEFT_RING_TOE("LeftRingToe", arrayOf(BodyPart.LEFT_RING_TOE)),
	LEFT_LITTLE_TOE("LeftLittleToe", arrayOf(BodyPart.LEFT_LITTLE_TOE)),
	RIGHT_BIG_TOE("RightBigToe", arrayOf(BodyPart.RIGHT_BIG_TOE)),
	RIGHT_INDEX_TOE("RightIndexToe", arrayOf(BodyPart.RIGHT_INDEX_TOE)),
	RIGHT_MIDDLE_TOE("RightMiddleToe", arrayOf(BodyPart.RIGHT_MIDDLE_TOE)),
	RIGHT_RING_TOE("RightRingToe", arrayOf(BodyPart.RIGHT_RING_TOE)),
	RIGHT_LITTLE_TOE("RightLittleToe", arrayOf(BodyPart.RIGHT_LITTLE_TOE)),
	;

	val opposite: UnityBone
		get() = when (this) {
			LEFT_SHOULDER -> RIGHT_SHOULDER
			RIGHT_SHOULDER -> LEFT_SHOULDER
			LEFT_UPPER_ARM -> RIGHT_UPPER_ARM
			RIGHT_UPPER_ARM -> LEFT_UPPER_ARM
			LEFT_LOWER_ARM -> RIGHT_LOWER_ARM
			RIGHT_LOWER_ARM -> LEFT_LOWER_ARM
			LEFT_HAND -> RIGHT_HAND
			RIGHT_HAND -> LEFT_HAND
			LEFT_UPPER_LEG -> RIGHT_UPPER_LEG
			RIGHT_UPPER_LEG -> LEFT_UPPER_LEG
			LEFT_LOWER_LEG -> RIGHT_LOWER_LEG
			RIGHT_LOWER_LEG -> LEFT_LOWER_LEG
			LEFT_FOOT -> RIGHT_FOOT
			RIGHT_FOOT -> LEFT_FOOT
			LEFT_THUMB_PROXIMAL -> RIGHT_THUMB_PROXIMAL
			RIGHT_THUMB_PROXIMAL -> LEFT_THUMB_PROXIMAL
			LEFT_THUMB_INTERMEDIATE -> RIGHT_THUMB_INTERMEDIATE
			RIGHT_THUMB_INTERMEDIATE -> LEFT_THUMB_INTERMEDIATE
			LEFT_THUMB_DISTAL -> RIGHT_THUMB_DISTAL
			RIGHT_THUMB_DISTAL -> LEFT_THUMB_DISTAL
			LEFT_INDEX_PROXIMAL -> RIGHT_INDEX_PROXIMAL
			RIGHT_INDEX_PROXIMAL -> LEFT_INDEX_PROXIMAL
			LEFT_INDEX_INTERMEDIATE -> RIGHT_INDEX_INTERMEDIATE
			RIGHT_INDEX_INTERMEDIATE -> LEFT_INDEX_INTERMEDIATE
			LEFT_INDEX_DISTAL -> RIGHT_INDEX_DISTAL
			RIGHT_INDEX_DISTAL -> LEFT_INDEX_DISTAL
			LEFT_MIDDLE_PROXIMAL -> RIGHT_MIDDLE_PROXIMAL
			RIGHT_MIDDLE_PROXIMAL -> LEFT_MIDDLE_PROXIMAL
			LEFT_MIDDLE_INTERMEDIATE -> RIGHT_MIDDLE_INTERMEDIATE
			RIGHT_MIDDLE_INTERMEDIATE -> LEFT_MIDDLE_INTERMEDIATE
			LEFT_MIDDLE_DISTAL -> RIGHT_MIDDLE_DISTAL
			RIGHT_MIDDLE_DISTAL -> LEFT_MIDDLE_DISTAL
			LEFT_RING_PROXIMAL -> RIGHT_RING_PROXIMAL
			RIGHT_RING_PROXIMAL -> LEFT_RING_PROXIMAL
			LEFT_RING_INTERMEDIATE -> RIGHT_RING_INTERMEDIATE
			RIGHT_RING_INTERMEDIATE -> LEFT_RING_INTERMEDIATE
			LEFT_RING_DISTAL -> RIGHT_RING_DISTAL
			RIGHT_RING_DISTAL -> LEFT_RING_DISTAL
			LEFT_LITTLE_PROXIMAL -> RIGHT_LITTLE_PROXIMAL
			RIGHT_LITTLE_PROXIMAL -> LEFT_LITTLE_PROXIMAL
			LEFT_LITTLE_INTERMEDIATE -> RIGHT_LITTLE_INTERMEDIATE
			RIGHT_LITTLE_INTERMEDIATE -> LEFT_LITTLE_INTERMEDIATE
			LEFT_LITTLE_DISTAL -> RIGHT_LITTLE_DISTAL
			RIGHT_LITTLE_DISTAL -> LEFT_LITTLE_DISTAL
			LEFT_TOES -> RIGHT_TOES
			RIGHT_TOES -> LEFT_TOES
			LEFT_BIG_TOE -> RIGHT_BIG_TOE
			RIGHT_BIG_TOE -> LEFT_BIG_TOE
			LEFT_INDEX_TOE -> RIGHT_INDEX_TOE
			RIGHT_INDEX_TOE -> LEFT_INDEX_TOE
			LEFT_MIDDLE_TOE -> RIGHT_MIDDLE_TOE
			RIGHT_MIDDLE_TOE -> LEFT_MIDDLE_TOE
			LEFT_RING_TOE -> RIGHT_RING_TOE
			RIGHT_RING_TOE -> LEFT_RING_TOE
			LEFT_LITTLE_TOE -> RIGHT_LITTLE_TOE
			RIGHT_LITTLE_TOE -> LEFT_LITTLE_TOE
			else -> this
		}

	companion object {
		fun fromSerial(serial: String): UnityBone? = entries.firstOrNull { it.serial.equals(serial, ignoreCase = true) }
	}
}
