/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/userguide/java_library_plugin.html
 */
plugins {
	kotlin("multiplatform")
	kotlin("plugin.serialization")
}

tasks.withType<Jar> {
	from("../../LICENSE-APACHE")
	from("../../LICENSE-MIT")
}

allprojects {
	repositories {
		// Use jcenter for resolving dependencies.
		// You can declare any Maven/Ivy/file repository here.
		mavenCentral()
		maven(url = "https://jitpack.io")
	}
}

kotlin {
	jvmToolchain(24)
	jvm()

	sourceSets {
		val commonMain by getting {
			kotlin.srcDir("src/main/java")
			dependencies {
				implementation(project(":solarxr-protocol:generated"))
				implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0")
				implementation("com.mayakapps.kache:kache:2.1.1")
				implementation("io.klogging:klogging:0.11.7")
				implementation("com.appstractive:dns-sd-kt:1.1.0")

				val ktorVersion = "3.4.1"
				implementation("io.ktor:ktor-client-core:$ktorVersion")
				implementation("io.ktor:ktor-client-cio:$ktorVersion")
				implementation("io.ktor:ktor-server-core:$ktorVersion")
				implementation("io.ktor:ktor-server-cio:$ktorVersion")
				implementation("io.ktor:ktor-network:$ktorVersion")
				implementation("io.ktor:ktor-utils:$ktorVersion")

				// Allow the use of reflection
				implementation(kotlin("reflect"))

				implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
				implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0")
			}
		}
		val commonTest by getting {
			kotlin.srcDir("src/test/java")
			dependencies {
				implementation(kotlin("test"))
				implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
			}
		}
	}
}

tasks.withType<JavaCompile> {
	options.encoding = "UTF-8"
}
tasks.withType<Test> {
	systemProperty("file.encoding", "UTF-8")
	useJUnitPlatform()
}
tasks.withType<Javadoc> {
	options.encoding = "UTF-8"
}
