package dev.slimevr.vr.processor.skeleton

import solarxr_protocol.datatypes.BodyPart

/**
 * Keys for all bones in the skeleton.
 */
// Why the hell does SolarXR translate enums to THISCASE in Kotlin...
enum class BoneType(val bodyPart: UByte = BodyPart.NONE) {
	HEAD(BodyPart.HEAD),
	NECK(BodyPart.NECK),
	CHEST(BodyPart.CHEST),
	CHEST_TRACKER,
	WAIST(BodyPart.WAIST),
	HIP(BodyPart.HIP),
	HIP_TRACKER,
	LEFT_HIP,
	RIGHT_HIP,
	LEFT_UPPER_LEG(BodyPart.LEFTUPPERLEG),
	RIGHT_UPPER_LEG(BodyPart.RIGHTUPPERLEG),
	LEFT_KNEE_TRACKER,
	RIGHT_KNEE_TRACKER,
	LEFT_LOWER_LEG(BodyPart.LEFTLOWERLEG),
	RIGHT_LOWER_LEG(BodyPart.RIGHTLOWERLEG),
	LEFT_FOOT(BodyPart.LEFTFOOT),
	RIGHT_FOOT(BodyPart.RIGHTFOOT),
	LEFT_FOOT_TRACKER(BodyPart.LEFTFOOT),
	RIGHT_FOOT_TRACKER(BodyPart.RIGHTFOOT),
	LEFT_CONTROLLER(BodyPart.LEFTCONTROLLER),
	RIGHT_CONTROLLER(BodyPart.RIGHTCONTROLLER),
	LEFT_LOWER_ARM(BodyPart.LEFTLOWERARM),
	RIGHT_LOWER_ARM(BodyPart.RIGHTLOWERARM),
    LEFT_ELBOW_TRACKER,
    RIGHT_ELBOW_TRACKER,
    UPPER_ARM,
    LEFT_UPPER_ARM(BodyPart.LEFTUPPERARM,),
	RIGHT_UPPER_ARM(BodyPart.RIGHTUPPERARM),
    LEFT_SHOULDER(BodyPart.LEFTSHOULDER),
    RIGHT_SHOULDER(BodyPart.RIGHTSHOULDER,),
	LEFT_HAND(BodyPart.LEFTHAND),
    RIGHT_HAND(BodyPart.RIGHTHAND),
    LEFT_HAND_TRACKER,
    RIGHT_HAND_TRACKER,
}
