// SolarXR has no BodyPart type on the wire: bones are opaque registry ids and string
// keys. This mirrors the server's own definition (server/core/.../bones/BodyPart.kt)
// by name, not by number, so a bone's id can be renumbered without breaking the GUI.
export enum BodyPart {
  NONE = 'NONE',
  HEAD = 'HEAD',
  NECK = 'NECK',
  UPPER_CHEST = 'UPPER_CHEST',
  LOWER_CHEST = 'LOWER_CHEST',
  UPPER_WAIST = 'UPPER_WAIST',
  LOWER_WAIST = 'LOWER_WAIST',
  HIP = 'HIP',
  LEFT_UPPER_LEG = 'LEFT_UPPER_LEG',
  RIGHT_UPPER_LEG = 'RIGHT_UPPER_LEG',
  LEFT_LOWER_LEG = 'LEFT_LOWER_LEG',
  RIGHT_LOWER_LEG = 'RIGHT_LOWER_LEG',
  LEFT_FOOT = 'LEFT_FOOT',
  RIGHT_FOOT = 'RIGHT_FOOT',
  LEFT_UPPER_ARM = 'LEFT_UPPER_ARM',
  RIGHT_UPPER_ARM = 'RIGHT_UPPER_ARM',
  LEFT_LOWER_ARM = 'LEFT_LOWER_ARM',
  RIGHT_LOWER_ARM = 'RIGHT_LOWER_ARM',
  LEFT_HAND = 'LEFT_HAND',
  RIGHT_HAND = 'RIGHT_HAND',
  LEFT_SHOULDER = 'LEFT_SHOULDER',
  RIGHT_SHOULDER = 'RIGHT_SHOULDER',
  LEFT_THUMB_METACARPAL = 'LEFT_THUMB_METACARPAL',
  LEFT_THUMB_PROXIMAL = 'LEFT_THUMB_PROXIMAL',
  LEFT_THUMB_DISTAL = 'LEFT_THUMB_DISTAL',
  LEFT_INDEX_PROXIMAL = 'LEFT_INDEX_PROXIMAL',
  LEFT_INDEX_INTERMEDIATE = 'LEFT_INDEX_INTERMEDIATE',
  LEFT_INDEX_DISTAL = 'LEFT_INDEX_DISTAL',
  LEFT_MIDDLE_PROXIMAL = 'LEFT_MIDDLE_PROXIMAL',
  LEFT_MIDDLE_INTERMEDIATE = 'LEFT_MIDDLE_INTERMEDIATE',
  LEFT_MIDDLE_DISTAL = 'LEFT_MIDDLE_DISTAL',
  LEFT_RING_PROXIMAL = 'LEFT_RING_PROXIMAL',
  LEFT_RING_INTERMEDIATE = 'LEFT_RING_INTERMEDIATE',
  LEFT_RING_DISTAL = 'LEFT_RING_DISTAL',
  LEFT_LITTLE_PROXIMAL = 'LEFT_LITTLE_PROXIMAL',
  LEFT_LITTLE_INTERMEDIATE = 'LEFT_LITTLE_INTERMEDIATE',
  LEFT_LITTLE_DISTAL = 'LEFT_LITTLE_DISTAL',
  RIGHT_THUMB_METACARPAL = 'RIGHT_THUMB_METACARPAL',
  RIGHT_THUMB_PROXIMAL = 'RIGHT_THUMB_PROXIMAL',
  RIGHT_THUMB_DISTAL = 'RIGHT_THUMB_DISTAL',
  RIGHT_INDEX_PROXIMAL = 'RIGHT_INDEX_PROXIMAL',
  RIGHT_INDEX_INTERMEDIATE = 'RIGHT_INDEX_INTERMEDIATE',
  RIGHT_INDEX_DISTAL = 'RIGHT_INDEX_DISTAL',
  RIGHT_MIDDLE_PROXIMAL = 'RIGHT_MIDDLE_PROXIMAL',
  RIGHT_MIDDLE_INTERMEDIATE = 'RIGHT_MIDDLE_INTERMEDIATE',
  RIGHT_MIDDLE_DISTAL = 'RIGHT_MIDDLE_DISTAL',
  RIGHT_RING_PROXIMAL = 'RIGHT_RING_PROXIMAL',
  RIGHT_RING_INTERMEDIATE = 'RIGHT_RING_INTERMEDIATE',
  RIGHT_RING_DISTAL = 'RIGHT_RING_DISTAL',
  RIGHT_LITTLE_PROXIMAL = 'RIGHT_LITTLE_PROXIMAL',
  RIGHT_LITTLE_INTERMEDIATE = 'RIGHT_LITTLE_INTERMEDIATE',
  RIGHT_LITTLE_DISTAL = 'RIGHT_LITTLE_DISTAL',
  LEFT_BIG_TOE = 'LEFT_BIG_TOE',
  LEFT_INDEX_TOE = 'LEFT_INDEX_TOE',
  LEFT_MIDDLE_TOE = 'LEFT_MIDDLE_TOE',
  LEFT_RING_TOE = 'LEFT_RING_TOE',
  LEFT_LITTLE_TOE = 'LEFT_LITTLE_TOE',
  RIGHT_BIG_TOE = 'RIGHT_BIG_TOE',
  RIGHT_INDEX_TOE = 'RIGHT_INDEX_TOE',
  RIGHT_MIDDLE_TOE = 'RIGHT_MIDDLE_TOE',
  RIGHT_RING_TOE = 'RIGHT_RING_TOE',
  RIGHT_LITTLE_TOE = 'RIGHT_LITTLE_TOE',
}

// Standard bones are keyed `slimevr:<lowercase name>` (BoneRegistry.standard on the
// server); this is the only way a wire BoneDefinition resolves back to a BodyPart.
const KEY_TO_BODY_PART: ReadonlyMap<string, BodyPart> = new Map(
  Object.values(BodyPart)
    .filter((value) => value !== BodyPart.NONE)
    .map((value) => [`slimevr:${value.toLowerCase()}`, value])
);

export function bodyPartOfKey(key: string): BodyPart {
  return KEY_TO_BODY_PART.get(key) ?? BodyPart.NONE;
}
