package dev.slimevr.resets

import solarxr_protocol.datatypes.BodyPart

object ResetBodyParts {
	val UPPER_LEGS = setOf(
		BodyPart.LEFT_UPPER_LEG,
		BodyPart.RIGHT_UPPER_LEG,
	)

	val LEFT_ARM = setOf(
		BodyPart.LEFT_SHOULDER,
		BodyPart.LEFT_UPPER_ARM,
		BodyPart.LEFT_LOWER_ARM,
		BodyPart.LEFT_HAND,
	)

	val RIGHT_ARM = setOf(
		BodyPart.RIGHT_SHOULDER,
		BodyPart.RIGHT_UPPER_ARM,
		BodyPart.RIGHT_LOWER_ARM,
		BodyPart.RIGHT_HAND,
	)

	val ARMS = LEFT_ARM + RIGHT_ARM

	val LEFT_LOWER_ARM = setOf(
		BodyPart.LEFT_LOWER_ARM,
		BodyPart.LEFT_HAND,
	)

	val RIGHT_LOWER_ARM = setOf(
		BodyPart.RIGHT_LOWER_ARM,
		BodyPart.RIGHT_HAND,
	)

	val LOWER_ARMS = LEFT_LOWER_ARM + RIGHT_LOWER_ARM

	val FEET = setOf(
		BodyPart.LEFT_FOOT,
		BodyPart.RIGHT_FOOT,
	)

	val LEFT_FINGERS = setOf(
		BodyPart.LEFT_THUMB_METACARPAL,
		BodyPart.LEFT_THUMB_PROXIMAL,
		BodyPart.LEFT_THUMB_DISTAL,
		BodyPart.LEFT_INDEX_PROXIMAL,
		BodyPart.LEFT_INDEX_INTERMEDIATE,
		BodyPart.LEFT_INDEX_DISTAL,
		BodyPart.LEFT_MIDDLE_PROXIMAL,
		BodyPart.LEFT_MIDDLE_INTERMEDIATE,
		BodyPart.LEFT_MIDDLE_DISTAL,
		BodyPart.LEFT_RING_PROXIMAL,
		BodyPart.LEFT_RING_INTERMEDIATE,
		BodyPart.LEFT_RING_DISTAL,
		BodyPart.LEFT_LITTLE_PROXIMAL,
		BodyPart.LEFT_LITTLE_INTERMEDIATE,
		BodyPart.LEFT_LITTLE_DISTAL,
	)

	val RIGHT_FINGERS = setOf(
		BodyPart.RIGHT_THUMB_METACARPAL,
		BodyPart.RIGHT_THUMB_PROXIMAL,
		BodyPart.RIGHT_THUMB_DISTAL,
		BodyPart.RIGHT_INDEX_PROXIMAL,
		BodyPart.RIGHT_INDEX_INTERMEDIATE,
		BodyPart.RIGHT_INDEX_DISTAL,
		BodyPart.RIGHT_MIDDLE_PROXIMAL,
		BodyPart.RIGHT_MIDDLE_INTERMEDIATE,
		BodyPart.RIGHT_MIDDLE_DISTAL,
		BodyPart.RIGHT_RING_PROXIMAL,
		BodyPart.RIGHT_RING_INTERMEDIATE,
		BodyPart.RIGHT_RING_DISTAL,
		BodyPart.RIGHT_LITTLE_PROXIMAL,
		BodyPart.RIGHT_LITTLE_INTERMEDIATE,
		BodyPart.RIGHT_LITTLE_DISTAL,
	)

	val LEFT_TOES = setOf(
		BodyPart.LEFT_BIG_TOE,
		BodyPart.LEFT_INDEX_TOE,
		BodyPart.LEFT_MIDDLE_TOE,
		BodyPart.LEFT_RING_TOE,
		BodyPart.LEFT_LITTLE_TOE,
	)
	val RIGHT_TOES = setOf(
		BodyPart.RIGHT_BIG_TOE,
		BodyPart.RIGHT_INDEX_TOE,
		BodyPart.RIGHT_MIDDLE_TOE,
		BodyPart.RIGHT_RING_TOE,
		BodyPart.RIGHT_LITTLE_TOE,
	)
}
