package dev.slimevr.resets

import solarxr_protocol.datatypes.BodyPart

object ResetBodyParts {
	val UPPER_LEGS = setOf(
		BodyPart.LEFT_UPPER_LEG,
		BodyPart.RIGHT_UPPER_LEG,
	)

	val FEET = setOf(
		BodyPart.LEFT_FOOT,
		BodyPart.RIGHT_FOOT,
	)

	val LEFT_FINGERS = setOf(
		BodyPart.LEFT_THUMB_METACARPAL,
		BodyPart.LEFT_THUMB_PROXIMAL,
		BodyPart.LEFT_THUMB_DISTAL,
		BodyPart.LEFT_INDEX_PROXIMAL,
		BodyPart.LEFT_INDEX_INTERMEDIATE,
		BodyPart.LEFT_INDEX_DISTAL,
		BodyPart.LEFT_MIDDLE_PROXIMAL,
		BodyPart.LEFT_MIDDLE_INTERMEDIATE,
		BodyPart.LEFT_MIDDLE_DISTAL,
		BodyPart.LEFT_RING_PROXIMAL,
		BodyPart.LEFT_RING_INTERMEDIATE,
		BodyPart.LEFT_RING_DISTAL,
		BodyPart.LEFT_LITTLE_PROXIMAL,
		BodyPart.LEFT_LITTLE_INTERMEDIATE,
		BodyPart.LEFT_LITTLE_DISTAL,
	)

	val RIGHT_FINGERS = setOf(
		BodyPart.RIGHT_THUMB_METACARPAL,
		BodyPart.RIGHT_THUMB_PROXIMAL,
		BodyPart.RIGHT_THUMB_DISTAL,
		BodyPart.RIGHT_INDEX_PROXIMAL,
		BodyPart.RIGHT_INDEX_INTERMEDIATE,
		BodyPart.RIGHT_INDEX_DISTAL,
		BodyPart.RIGHT_MIDDLE_PROXIMAL,
		BodyPart.RIGHT_MIDDLE_INTERMEDIATE,
		BodyPart.RIGHT_MIDDLE_DISTAL,
		BodyPart.RIGHT_RING_PROXIMAL,
		BodyPart.RIGHT_RING_INTERMEDIATE,
		BodyPart.RIGHT_RING_DISTAL,
		BodyPart.RIGHT_LITTLE_PROXIMAL,
		BodyPart.RIGHT_LITTLE_INTERMEDIATE,
		BodyPart.RIGHT_LITTLE_DISTAL,
	)

	val LEFT_LOWER_ARM = setOf(
		BodyPart.LEFT_LOWER_ARM,
		BodyPart.LEFT_HAND,
	) + LEFT_FINGERS

	val RIGHT_LOWER_ARM = setOf(
		BodyPart.RIGHT_LOWER_ARM,
		BodyPart.RIGHT_HAND,
	) + RIGHT_FINGERS

	val LOWER_ARMS = LEFT_LOWER_ARM + RIGHT_LOWER_ARM

	val LEFT_ARM = setOf(
		BodyPart.LEFT_SHOULDER,
		BodyPart.LEFT_UPPER_ARM,
	) + LEFT_LOWER_ARM

	val RIGHT_ARM = setOf(
		BodyPart.RIGHT_SHOULDER,
		BodyPart.RIGHT_UPPER_ARM,
	) + RIGHT_LOWER_ARM

	val ARMS = LEFT_ARM + RIGHT_ARM
}
