package dev.slimevr.resets

import solarxr_protocol.datatypes.BodyPart

val UPPER_LEG_PARTS = setOf(
	BodyPart.LEFT_UPPER_LEG,
	BodyPart.RIGHT_UPPER_LEG,
)

val LEFT_ARM_PARTS = setOf(
	BodyPart.LEFT_SHOULDER,
	BodyPart.LEFT_UPPER_ARM,
	BodyPart.LEFT_LOWER_ARM,
	BodyPart.LEFT_HAND,
)

val RIGHT_ARM_PARTS = setOf(
	BodyPart.RIGHT_SHOULDER,
	BodyPart.RIGHT_UPPER_ARM,
	BodyPart.RIGHT_LOWER_ARM,
	BodyPart.RIGHT_HAND,
)

val ARM_PARTS = LEFT_ARM_PARTS + RIGHT_ARM_PARTS

val LEFT_LOWER_ARM_PARTS = setOf(
	BodyPart.LEFT_LOWER_ARM,
	BodyPart.LEFT_HAND,
)

val RIGHT_LOWER_ARM_PARTS = setOf(
	BodyPart.RIGHT_LOWER_ARM,
	BodyPart.RIGHT_HAND,
)

val LOWER_ARM_PARTS = LEFT_LOWER_ARM_PARTS + RIGHT_LOWER_ARM_PARTS

val FOOT_PARTS = setOf(
	BodyPart.LEFT_FOOT,
	BodyPart.RIGHT_FOOT,
)

val LEFT_FINGER_PARTS = setOf(
	BodyPart.LEFT_THUMB_METACARPAL,
	BodyPart.LEFT_THUMB_PROXIMAL,
	BodyPart.LEFT_THUMB_DISTAL,
	BodyPart.LEFT_INDEX_PROXIMAL,
	BodyPart.LEFT_INDEX_INTERMEDIATE,
	BodyPart.LEFT_INDEX_DISTAL,
	BodyPart.LEFT_MIDDLE_PROXIMAL,
	BodyPart.LEFT_MIDDLE_INTERMEDIATE,
	BodyPart.LEFT_MIDDLE_DISTAL,
	BodyPart.LEFT_RING_PROXIMAL,
	BodyPart.LEFT_RING_INTERMEDIATE,
	BodyPart.LEFT_RING_DISTAL,
	BodyPart.LEFT_LITTLE_PROXIMAL,
	BodyPart.LEFT_LITTLE_INTERMEDIATE,
	BodyPart.LEFT_LITTLE_DISTAL,
)

val RIGHT_FINGER_PARTS = setOf(
	BodyPart.RIGHT_THUMB_METACARPAL,
	BodyPart.RIGHT_THUMB_PROXIMAL,
	BodyPart.RIGHT_THUMB_DISTAL,
	BodyPart.RIGHT_INDEX_PROXIMAL,
	BodyPart.RIGHT_INDEX_INTERMEDIATE,
	BodyPart.RIGHT_INDEX_DISTAL,
	BodyPart.RIGHT_MIDDLE_PROXIMAL,
	BodyPart.RIGHT_MIDDLE_INTERMEDIATE,
	BodyPart.RIGHT_MIDDLE_DISTAL,
	BodyPart.RIGHT_RING_PROXIMAL,
	BodyPart.RIGHT_RING_INTERMEDIATE,
	BodyPart.RIGHT_RING_DISTAL,
	BodyPart.RIGHT_LITTLE_PROXIMAL,
	BodyPart.RIGHT_LITTLE_INTERMEDIATE,
	BodyPart.RIGHT_LITTLE_DISTAL,
)
