#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

case "$(uname -sr)" in
	CYGWIN*|MINGW*|MINGW32*|MSYS*)
		./gradlew.bat spotlessApply
		npx.cmd -w gui lint-staged
		;;

	*)
		./gradlew spotlessApply
		npx -w gui lint-staged
		;;
esac
