package dev.slimevr.skeleton

import solarxr_protocol.datatypes.BodyPart

val BODY_PART_HIERARCHY_MAP: Map<BodyPart, Array<BodyPart>> = mapOf(
	BodyPart.HEAD to arrayOf(BodyPart.NECK),
	BodyPart.NECK to arrayOf(BodyPart.UPPER_CHEST, BodyPart.LEFT_SHOULDER, BodyPart.RIGHT_SHOULDER),

	BodyPart.LEFT_SHOULDER to arrayOf(BodyPart.LEFT_UPPER_ARM),
	BodyPart.LEFT_UPPER_ARM to arrayOf(BodyPart.LEFT_LOWER_ARM),
	BodyPart.LEFT_LOWER_ARM to arrayOf(BodyPart.LEFT_HAND),

	BodyPart.LEFT_HAND to arrayOf(
		BodyPart.LEFT_THUMB_METACARPAL,
		BodyPart.LEFT_INDEX_PROXIMAL,
		BodyPart.LEFT_MIDDLE_PROXIMAL,
		BodyPart.LEFT_RING_PROXIMAL,
		BodyPart.LEFT_LITTLE_PROXIMAL,
	),
	BodyPart.LEFT_THUMB_METACARPAL to arrayOf(BodyPart.LEFT_THUMB_PROXIMAL),
	BodyPart.LEFT_THUMB_PROXIMAL to arrayOf(BodyPart.LEFT_THUMB_DISTAL),
	BodyPart.LEFT_INDEX_PROXIMAL to arrayOf(BodyPart.LEFT_INDEX_INTERMEDIATE),
	BodyPart.LEFT_INDEX_INTERMEDIATE to arrayOf(BodyPart.LEFT_INDEX_DISTAL),
	BodyPart.LEFT_MIDDLE_PROXIMAL to arrayOf(BodyPart.LEFT_MIDDLE_INTERMEDIATE),
	BodyPart.LEFT_MIDDLE_INTERMEDIATE to arrayOf(BodyPart.LEFT_MIDDLE_DISTAL),
	BodyPart.LEFT_RING_PROXIMAL to arrayOf(BodyPart.LEFT_RING_INTERMEDIATE),
	BodyPart.LEFT_RING_INTERMEDIATE to arrayOf(BodyPart.LEFT_RING_DISTAL),
	BodyPart.LEFT_LITTLE_PROXIMAL to arrayOf(BodyPart.LEFT_LITTLE_INTERMEDIATE),
	BodyPart.LEFT_LITTLE_INTERMEDIATE to arrayOf(BodyPart.LEFT_LITTLE_DISTAL),

	BodyPart.RIGHT_SHOULDER to arrayOf(BodyPart.RIGHT_UPPER_ARM),
	BodyPart.RIGHT_UPPER_ARM to arrayOf(BodyPart.RIGHT_LOWER_ARM),
	BodyPart.RIGHT_LOWER_ARM to arrayOf(BodyPart.RIGHT_HAND),

	BodyPart.RIGHT_HAND to arrayOf(
		BodyPart.RIGHT_THUMB_METACARPAL,
		BodyPart.RIGHT_INDEX_PROXIMAL,
		BodyPart.RIGHT_MIDDLE_PROXIMAL,
		BodyPart.RIGHT_RING_PROXIMAL,
		BodyPart.RIGHT_LITTLE_PROXIMAL,
	),
	BodyPart.RIGHT_THUMB_METACARPAL to arrayOf(BodyPart.RIGHT_THUMB_PROXIMAL),
	BodyPart.RIGHT_THUMB_PROXIMAL to arrayOf(BodyPart.RIGHT_THUMB_DISTAL),
	BodyPart.RIGHT_INDEX_PROXIMAL to arrayOf(BodyPart.RIGHT_INDEX_INTERMEDIATE),
	BodyPart.RIGHT_INDEX_INTERMEDIATE to arrayOf(BodyPart.RIGHT_INDEX_DISTAL),
	BodyPart.RIGHT_MIDDLE_PROXIMAL to arrayOf(BodyPart.RIGHT_MIDDLE_INTERMEDIATE),
	BodyPart.RIGHT_MIDDLE_INTERMEDIATE to arrayOf(BodyPart.RIGHT_MIDDLE_DISTAL),
	BodyPart.RIGHT_RING_PROXIMAL to arrayOf(BodyPart.RIGHT_RING_INTERMEDIATE),
	BodyPart.RIGHT_RING_INTERMEDIATE to arrayOf(BodyPart.RIGHT_RING_DISTAL),
	BodyPart.RIGHT_LITTLE_PROXIMAL to arrayOf(BodyPart.RIGHT_LITTLE_INTERMEDIATE),
	BodyPart.RIGHT_LITTLE_INTERMEDIATE to arrayOf(BodyPart.RIGHT_LITTLE_DISTAL),

	BodyPart.UPPER_CHEST to arrayOf(BodyPart.LOWER_CHEST),
	BodyPart.LOWER_CHEST to arrayOf(BodyPart.UPPER_WAIST),
	BodyPart.UPPER_WAIST to arrayOf(BodyPart.LOWER_WAIST),
	BodyPart.LOWER_WAIST to arrayOf(BodyPart.HIP),
	BodyPart.HIP to arrayOf(BodyPart.LEFT_UPPER_LEG, BodyPart.RIGHT_UPPER_LEG),

	BodyPart.LEFT_UPPER_LEG to arrayOf(BodyPart.LEFT_LOWER_LEG),
	BodyPart.LEFT_LOWER_LEG to arrayOf(BodyPart.LEFT_FOOT),

	BodyPart.RIGHT_UPPER_LEG to arrayOf(BodyPart.RIGHT_LOWER_LEG),
	BodyPart.RIGHT_LOWER_LEG to arrayOf(BodyPart.RIGHT_FOOT),

	BodyPart.LEFT_FOOT to arrayOf(
		BodyPart.LEFT_BIG_TOE,
		BodyPart.LEFT_INDEX_TOE,
		BodyPart.LEFT_MIDDLE_TOE,
		BodyPart.LEFT_RING_TOE,
		BodyPart.LEFT_LITTLE_TOE,
	),

	BodyPart.RIGHT_FOOT to arrayOf(
		BodyPart.RIGHT_BIG_TOE,
		BodyPart.RIGHT_INDEX_TOE,
		BodyPart.RIGHT_MIDDLE_TOE,
		BodyPart.RIGHT_RING_TOE,
		BodyPart.RIGHT_LITTLE_TOE,
	),
)
